language: python

sudo: false

dist: trusty
group: edge

python:
   - "3.5"
   - "3.6"

os:
  - linux


install:
  - pip install --upgrade pip
  - python setup.py build_ext --inplace
  - pip install .

script:
  - "python setup.py test"
