language: python

sudo: false
dist: trusty
group: edge

python:
   - "3.5"
   - "3.6"

os:
  - linux

env:
  - VIA=compile

install:
  - python setup.py build_ext --inplace
  - pip install -e .

script:
  - "python setup.py test"
